#!/bin/sh

set -e

ulimit -H -l unlimited 2>/dev/null || {
    # https://bugs.launchpad.net/bugs/1828228
    echo "test disabled for unprivileged namespaces"
    exit 77
}

# Ubuntu uses http proxy breaking some tests
unset http_proxy
unset https_proxy

cat >>/etc/hosts <<EOF

192.168.1.1 rh7-1 rh7-1.localhost
192.168.1.2 rh7-2 rh7-2.localhost
192.168.1.3 rh7-3 rh7-3.localhost
EOF

python3 ./pcs_test/suite.py --fast-info -v 2>&1
