#!/bin/sh

set -e

ulimit -H -l unlimited 2>/dev/null || {
    # https://bugs.launchpad.net/bugs/1828228
    echo "test disabled for unprivileged namespaces"
    exit 77
}

OUTPUT="${AUTOPKGTEST_ARTIFACTS:-.}/cfgtool.txt"

corosync-cfgtool -s >"$OUTPUT"
cat "$OUTPUT"
grep -q 'nodeid  1:	link enabled:1	link connected:1' "$OUTPUT"
