#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:		pcs_snmp_agent
# Required-Start:	$remote_fs $syslog snmpd
# Required-Stop:	$remote_fs $syslog snmpd
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	SNMP agent for pacemaker cluster
# Description:		Starts and stops pcs SNMP agent.
### END INIT INFO

NAME="pcs_snmp_agent"
DESC="SNMP agent for pacemaker cluster"
DAEMON="/usr/share/pcs/$NAME"
START_ARGS="--background --make-pidfile"

do_stop_override() {
    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 \
                      --pidfile ${PIDFILE} --exec /usr/bin/python3
}
