#!/bin/sh

set -e

DISK=$AUTOPKGTEST_TMP/disk

cleanup () {
  rm -f $DISK || true
}

trap "cleanup" 0 2 3 15

# create test disk
echo "=== disk ==="
dd if=/dev/zero of=$DISK bs=1M count=200 2>&1

# test tools
echo "=== mkfs ==="
mkfs.gfs2 -p lock_nolock -t debian:basic -J 32 -j 2 -O $DISK

echo "=== fsck ==="
fsck.gfs2 -f -y $DISK 2>&1

echo "=== convert ==="
gfs2_convert $DISK 2>&1 | grep -20 'does not look like a gfs1 filesystem'

echo "=== edit ==="
gfs2_edit -p sb $DISK

echo "=== tunefs ==="
tunegfs2 -l $DISK
